// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="system_top_system_top,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.119917,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=19995,HLS_SYN_LUT=55711,HLS_VERSION=2020_2}" *)

module system_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        points_address0,
        points_ce0,
        points_q0,
        points_address1,
        points_ce1,
        points_q1,
        num_points_address0,
        num_points_ce0,
        num_points_q0,
        num_points_address1,
        num_points_ce1,
        num_points_q1,
        patch_stream_V_din,
        patch_stream_V_full_n,
        patch_stream_V_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_pp0_stage0 = 10'd2;
parameter    ap_ST_fsm_state4 = 10'd4;
parameter    ap_ST_fsm_pp1_stage0 = 10'd8;
parameter    ap_ST_fsm_state7 = 10'd16;
parameter    ap_ST_fsm_pp2_stage0 = 10'd32;
parameter    ap_ST_fsm_state10 = 10'd64;
parameter    ap_ST_fsm_state11 = 10'd128;
parameter    ap_ST_fsm_state12 = 10'd256;
parameter    ap_ST_fsm_state13 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] points_address0;
output   points_ce0;
input  [127:0] points_q0;
output  [11:0] points_address1;
output   points_ce1;
input  [127:0] points_q1;
output  [2:0] num_points_address0;
output   num_points_ce0;
input  [31:0] num_points_q0;
output  [2:0] num_points_address1;
output   num_points_ce1;
input  [31:0] num_points_q1;
output  [95:0] patch_stream_V_din;
input   patch_stream_V_full_n;
output   patch_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg patch_stream_V_write;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] latest_patch_index_constprop;
reg   [31:0] num_patches_constprop;
wire   [1:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_address0;
reg    system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_ce0;
wire   [0:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_q0;
wire   [1:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_address0;
reg    system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_ce0;
wire   [0:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_q0;
wire   [1:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_address0;
reg    system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_ce0;
wire   [0:0] system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_q0;
reg   [1:0] loop_index80_reg_239;
reg   [1:0] loop_index77_reg_250;
reg   [1:0] loop_index_reg_261;
wire   [1:0] empty_fu_339_p2;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] exitcond834_fu_345_p2;
reg   [0:0] exitcond834_reg_412;
wire   [63:0] loop_index80_cast_fu_351_p1;
reg   [63:0] loop_index80_cast_reg_416;
wire   [1:0] empty_56_fu_356_p2;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state5_pp1_stage0_iter0;
wire    ap_block_state6_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] exitcond823_fu_362_p2;
reg   [0:0] exitcond823_reg_431;
wire   [63:0] loop_index77_cast_fu_368_p1;
reg   [63:0] loop_index77_cast_reg_435;
wire   [1:0] empty_58_fu_373_p2;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state8_pp2_stage0_iter0;
wire    ap_block_state9_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond812_fu_379_p2;
reg   [0:0] exitcond812_reg_450;
wire   [63:0] loop_index_cast_fu_385_p1;
reg   [63:0] loop_index_cast_reg_454;
wire   [1:0] empty_61_fu_390_p2;
wire    ap_CS_fsm_state11;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_CS_fsm_state4;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state5;
reg    ap_enable_reg_pp1_iter1;
wire    ap_CS_fsm_state7;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state8;
reg    ap_enable_reg_pp2_iter1;
wire   [31:0] patch_buffer_q0;
wire   [31:0] patch_buffer_q1;
wire   [31:0] shadow_bottomL_jR_q0;
wire   [31:0] shadow_bottomL_jR_q1;
wire   [31:0] shadow_bottomR_jR_q0;
wire   [31:0] shadow_bottomR_jR_q1;
wire   [31:0] shadow_bottomL_jL_q0;
wire   [31:0] shadow_bottomL_jL_q1;
wire   [31:0] shadow_bottomR_jL_q0;
wire   [31:0] shadow_bottomR_jL_q1;
wire   [25:0] z1_min_q0;
wire   [25:0] z1_max_q0;
wire   [31:0] a_corner_1_q0;
wire   [31:0] b_corner_1_q0;
wire   [25:0] c_corner_0_q0;
wire   [31:0] c_corner_1_q0;
wire   [31:0] d_corner_1_q0;
reg   [1:0] squareAcceptance_address0;
reg    squareAcceptance_ce0;
reg    squareAcceptance_we0;
reg   [0:0] squareAcceptance_d0;
wire   [0:0] squareAcceptance_q0;
reg   [1:0] flatTop_address0;
reg    flatTop_ce0;
reg    flatTop_we0;
reg   [0:0] flatTop_d0;
reg   [1:0] flatBottom_address0;
reg    flatBottom_ce0;
reg    flatBottom_we0;
reg   [0:0] flatBottom_d0;
wire   [0:0] flatBottom_q0;
reg   [1:0] triangleAcceptance_address0;
reg    triangleAcceptance_ce0;
reg    triangleAcceptance_we0;
reg   [0:0] triangleAcceptance_d0;
wire   [0:0] triangleAcceptance_q0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_done;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_idle;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_ready;
wire   [11:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce0;
wire   [11:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce1;
wire   [2:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce0;
wire   [2:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce1;
wire   [95:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_din;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_write;
wire   [7:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d0;
wire   [7:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we1;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d1;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce1;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce1;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce1;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address1;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce1;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_d0;
wire   [3:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_we0;
wire   [25:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_we0;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_we0;
wire   [0:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_we0;
wire   [0:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_we0;
wire   [0:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_address0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_ce0;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_we0;
wire   [0:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_d0;
wire   [1:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o_ap_vld;
wire   [31:0] grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o;
wire    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o_ap_vld;
reg   [1:0] empty_60_reg_272;
wire   [0:0] exitcond1_fu_396_p2;
wire    ap_CS_fsm_state10;
reg    grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_block_pp0_stage0;
wire    ap_block_pp1_stage0;
wire    ap_block_pp2_stage0;
wire   [63:0] p_cast_fu_402_p1;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 latest_patch_index_constprop = 2'd0;
#0 num_patches_constprop = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg = 1'b0;
end

system_top_system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_address0),
    .ce0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_ce0),
    .q0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_q0)
);

system_top_system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_address0),
    .ce0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_ce0),
    .q0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_q0)
);

system_top_system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_address0),
    .ce0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_ce0),
    .q0(system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_q0)
);

system_top_patch_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 240 ),
    .AddressWidth( 8 ))
patch_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d0),
    .q0(patch_buffer_q0),
    .address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address1),
    .ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce1),
    .we1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we1),
    .d1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d1),
    .q1(patch_buffer_q1)
);

system_top_pSlope #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
pSlope_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_d0)
);

system_top_shadow_bottomL_jR #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
shadow_bottomL_jR_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_d0),
    .q0(shadow_bottomL_jR_q0),
    .address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address1),
    .ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce1),
    .q1(shadow_bottomL_jR_q1)
);

system_top_shadow_bottomL_jR #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
shadow_bottomR_jR_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_d0),
    .q0(shadow_bottomR_jR_q0),
    .address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address1),
    .ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce1),
    .q1(shadow_bottomR_jR_q1)
);

system_top_shadow_bottomL_jR #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
shadow_bottomL_jL_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_d0),
    .q0(shadow_bottomL_jL_q0),
    .address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address1),
    .ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce1),
    .q1(shadow_bottomL_jL_q1)
);

system_top_shadow_bottomL_jR #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
shadow_bottomR_jL_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_d0),
    .q0(shadow_bottomR_jL_q0),
    .address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address1),
    .ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce1),
    .q1(shadow_bottomR_jL_q1)
);

system_top_z1_min #(
    .DataWidth( 26 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
z1_min_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_d0),
    .q0(z1_min_q0)
);

system_top_z1_min #(
    .DataWidth( 26 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
z1_max_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_d0),
    .q0(z1_max_q0)
);

system_top_a_corner_0 #(
    .DataWidth( 26 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
a_corner_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_d0)
);

system_top_a_corner_1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
a_corner_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_d0),
    .q0(a_corner_1_q0)
);

system_top_a_corner_0 #(
    .DataWidth( 26 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
b_corner_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_d0)
);

system_top_a_corner_1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
b_corner_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_d0),
    .q0(b_corner_1_q0)
);

system_top_c_corner_0 #(
    .DataWidth( 26 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
c_corner_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_d0),
    .q0(c_corner_0_q0)
);

system_top_a_corner_1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
c_corner_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_d0),
    .q0(c_corner_1_q0)
);

system_top_a_corner_0 #(
    .DataWidth( 26 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
d_corner_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_d0)
);

system_top_a_corner_1 #(
    .DataWidth( 32 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
d_corner_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_address0),
    .ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_ce0),
    .we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_we0),
    .d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_d0),
    .q0(d_corner_1_q0)
);

system_top_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
squareAcceptance_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(squareAcceptance_address0),
    .ce0(squareAcceptance_ce0),
    .we0(squareAcceptance_we0),
    .d0(squareAcceptance_d0),
    .q0(squareAcceptance_q0)
);

system_top_flatTop #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
flatTop_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(flatTop_address0),
    .ce0(flatTop_ce0),
    .we0(flatTop_we0),
    .d0(flatTop_d0)
);

system_top_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
flatBottom_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(flatBottom_address0),
    .ce0(flatBottom_ce0),
    .we0(flatBottom_we0),
    .d0(flatBottom_d0),
    .q0(flatBottom_q0)
);

system_top_squareAcceptance #(
    .DataWidth( 1 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
triangleAcceptance_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangleAcceptance_address0),
    .ce0(triangleAcceptance_ce0),
    .we0(triangleAcceptance_we0),
    .d0(triangleAcceptance_d0),
    .q0(triangleAcceptance_q0)
);

system_top_p_shadowquilt_main_loop_make_verticle_strip grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start),
    .ap_done(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_done),
    .ap_idle(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_idle),
    .ap_ready(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_ready),
    .points_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address0),
    .points_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce0),
    .points_q0(points_q0),
    .points_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address1),
    .points_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce1),
    .points_q1(points_q1),
    .num_points_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address0),
    .num_points_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce0),
    .num_points_q0(num_points_q0),
    .num_points_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address1),
    .num_points_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce1),
    .num_points_q1(num_points_q1),
    .patch_stream_V_din(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_din),
    .patch_stream_V_full_n(patch_stream_V_full_n),
    .patch_stream_V_write(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_write),
    .patch_buffer_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address0),
    .patch_buffer_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce0),
    .patch_buffer_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we0),
    .patch_buffer_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d0),
    .patch_buffer_q0(patch_buffer_q0),
    .patch_buffer_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_address1),
    .patch_buffer_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_ce1),
    .patch_buffer_we1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_we1),
    .patch_buffer_d1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_buffer_d1),
    .patch_buffer_q1(patch_buffer_q1),
    .pSlope_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_address0),
    .pSlope_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_ce0),
    .pSlope_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_we0),
    .pSlope_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_pSlope_d0),
    .shadow_bottomL_jR_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address0),
    .shadow_bottomL_jR_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce0),
    .shadow_bottomL_jR_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_we0),
    .shadow_bottomL_jR_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_d0),
    .shadow_bottomL_jR_q0(shadow_bottomL_jR_q0),
    .shadow_bottomL_jR_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_address1),
    .shadow_bottomL_jR_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jR_ce1),
    .shadow_bottomL_jR_q1(shadow_bottomL_jR_q1),
    .shadow_bottomR_jR_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address0),
    .shadow_bottomR_jR_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce0),
    .shadow_bottomR_jR_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_we0),
    .shadow_bottomR_jR_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_d0),
    .shadow_bottomR_jR_q0(shadow_bottomR_jR_q0),
    .shadow_bottomR_jR_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_address1),
    .shadow_bottomR_jR_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jR_ce1),
    .shadow_bottomR_jR_q1(shadow_bottomR_jR_q1),
    .shadow_bottomL_jL_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address0),
    .shadow_bottomL_jL_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce0),
    .shadow_bottomL_jL_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_we0),
    .shadow_bottomL_jL_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_d0),
    .shadow_bottomL_jL_q0(shadow_bottomL_jL_q0),
    .shadow_bottomL_jL_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_address1),
    .shadow_bottomL_jL_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomL_jL_ce1),
    .shadow_bottomL_jL_q1(shadow_bottomL_jL_q1),
    .shadow_bottomR_jL_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address0),
    .shadow_bottomR_jL_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce0),
    .shadow_bottomR_jL_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_we0),
    .shadow_bottomR_jL_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_d0),
    .shadow_bottomR_jL_q0(shadow_bottomR_jL_q0),
    .shadow_bottomR_jL_address1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_address1),
    .shadow_bottomR_jL_ce1(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_shadow_bottomR_jL_ce1),
    .shadow_bottomR_jL_q1(shadow_bottomR_jL_q1),
    .z1_min_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_address0),
    .z1_min_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_ce0),
    .z1_min_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_we0),
    .z1_min_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_min_d0),
    .z1_min_q0(z1_min_q0),
    .z1_max_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_address0),
    .z1_max_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_ce0),
    .z1_max_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_we0),
    .z1_max_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_z1_max_d0),
    .z1_max_q0(z1_max_q0),
    .a_corner_0_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_address0),
    .a_corner_0_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_ce0),
    .a_corner_0_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_we0),
    .a_corner_0_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_0_d0),
    .a_corner_1_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_address0),
    .a_corner_1_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_ce0),
    .a_corner_1_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_we0),
    .a_corner_1_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_a_corner_1_d0),
    .a_corner_1_q0(a_corner_1_q0),
    .b_corner_0_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_address0),
    .b_corner_0_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_ce0),
    .b_corner_0_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_we0),
    .b_corner_0_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_0_d0),
    .b_corner_1_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_address0),
    .b_corner_1_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_ce0),
    .b_corner_1_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_we0),
    .b_corner_1_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_b_corner_1_d0),
    .b_corner_1_q0(b_corner_1_q0),
    .c_corner_0_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_address0),
    .c_corner_0_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_ce0),
    .c_corner_0_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_we0),
    .c_corner_0_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_0_d0),
    .c_corner_0_q0(c_corner_0_q0),
    .c_corner_1_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_address0),
    .c_corner_1_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_ce0),
    .c_corner_1_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_we0),
    .c_corner_1_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_c_corner_1_d0),
    .c_corner_1_q0(c_corner_1_q0),
    .d_corner_0_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_address0),
    .d_corner_0_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_ce0),
    .d_corner_0_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_we0),
    .d_corner_0_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_0_d0),
    .d_corner_1_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_address0),
    .d_corner_1_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_ce0),
    .d_corner_1_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_we0),
    .d_corner_1_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_d_corner_1_d0),
    .d_corner_1_q0(d_corner_1_q0),
    .squareAcceptance_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_address0),
    .squareAcceptance_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_ce0),
    .squareAcceptance_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_we0),
    .squareAcceptance_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_d0),
    .squareAcceptance_q0(squareAcceptance_q0),
    .flatTop_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_address0),
    .flatTop_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_ce0),
    .flatTop_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_we0),
    .flatTop_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_d0),
    .flatBottom_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_address0),
    .flatBottom_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_ce0),
    .flatBottom_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_we0),
    .flatBottom_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_d0),
    .flatBottom_q0(flatBottom_q0),
    .triangleAcceptance_address0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_address0),
    .triangleAcceptance_ce0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_ce0),
    .triangleAcceptance_we0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_we0),
    .triangleAcceptance_d0(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_d0),
    .triangleAcceptance_q0(triangleAcceptance_q0),
    .latest_patch_index_constprop_i(latest_patch_index_constprop),
    .latest_patch_index_constprop_o(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o),
    .latest_patch_index_constprop_o_ap_vld(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o_ap_vld),
    .num_patches_constprop_i(num_patches_constprop),
    .num_patches_constprop_o(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o),
    .num_patches_constprop_o_ap_vld(grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state5))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state8))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_ready == 1'b1)) begin
            grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_60_reg_272 <= 2'd0;
    end else if (((exitcond1_fu_396_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_60_reg_272 <= empty_61_fu_390_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        latest_patch_index_constprop <= 2'd0;
    end else if (((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        latest_patch_index_constprop <= grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_latest_patch_index_constprop_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        loop_index77_reg_250 <= 2'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond823_fu_362_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        loop_index77_reg_250 <= empty_56_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond834_fu_345_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_index80_reg_239 <= empty_fu_339_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        loop_index80_reg_239 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        loop_index_reg_261 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond812_fu_379_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        loop_index_reg_261 <= empty_58_fu_373_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        num_patches_constprop <= 32'd0;
    end else if (((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        num_patches_constprop <= grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_patches_constprop_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        exitcond812_reg_450 <= exitcond812_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond823_reg_431 <= exitcond823_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond834_reg_412 <= exitcond834_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond823_fu_362_p2 == 1'd0))) begin
        loop_index77_cast_reg_435[1 : 0] <= loop_index77_cast_fu_368_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond834_fu_345_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        loop_index80_cast_reg_416[1 : 0] <= loop_index80_cast_fu_351_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond812_fu_379_p2 == 1'd0))) begin
        loop_index_cast_reg_454[1 : 0] <= loop_index_cast_fu_385_p1[1 : 0];
    end
end

always @ (*) begin
    if ((exitcond834_fu_345_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond823_fu_362_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond812_fu_379_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        flatBottom_address0 = loop_index_cast_reg_454;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatBottom_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_address0;
    end else begin
        flatBottom_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        flatBottom_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatBottom_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_ce0;
    end else begin
        flatBottom_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        flatBottom_d0 = system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatBottom_d0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_d0;
    end else begin
        flatBottom_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond812_reg_450 == 1'd0))) begin
        flatBottom_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatBottom_we0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatBottom_we0;
    end else begin
        flatBottom_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        flatTop_address0 = loop_index77_cast_reg_435;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatTop_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_address0;
    end else begin
        flatTop_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        flatTop_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatTop_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_ce0;
    end else begin
        flatTop_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        flatTop_d0 = system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatTop_d0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_d0;
    end else begin
        flatTop_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (exitcond823_reg_431 == 1'd0))) begin
        flatTop_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        flatTop_we0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_flatTop_we0;
    end else begin
        flatTop_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        patch_stream_V_write = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_write;
    end else begin
        patch_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        squareAcceptance_address0 = loop_index80_cast_reg_416;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        squareAcceptance_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_address0;
    end else begin
        squareAcceptance_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        squareAcceptance_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        squareAcceptance_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_ce0;
    end else begin
        squareAcceptance_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        squareAcceptance_d0 = system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        squareAcceptance_d0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_d0;
    end else begin
        squareAcceptance_d0 = 'bx;
    end
end

always @ (*) begin
    if (((exitcond834_reg_412 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        squareAcceptance_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        squareAcceptance_we0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_squareAcceptance_we0;
    end else begin
        squareAcceptance_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_ce0 = 1'b1;
    end else begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_ce0 = 1'b1;
    end else begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_ce0 = 1'b1;
    end else begin
        system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triangleAcceptance_address0 = p_cast_fu_402_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        triangleAcceptance_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_address0;
    end else begin
        triangleAcceptance_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triangleAcceptance_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        triangleAcceptance_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_ce0;
    end else begin
        triangleAcceptance_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        triangleAcceptance_d0 = 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        triangleAcceptance_d0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_d0;
    end else begin
        triangleAcceptance_d0 = 'bx;
    end
end

always @ (*) begin
    if (((exitcond1_fu_396_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        triangleAcceptance_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        triangleAcceptance_we0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_triangleAcceptance_we0;
    end else begin
        triangleAcceptance_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond834_fu_345_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond834_fu_345_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (exitcond823_fu_362_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (exitcond823_fu_362_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond812_fu_379_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond812_fu_379_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((exitcond1_fu_396_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign empty_56_fu_356_p2 = (loop_index77_reg_250 + 2'd1);

assign empty_58_fu_373_p2 = (loop_index_reg_261 + 2'd1);

assign empty_61_fu_390_p2 = (empty_60_reg_272 + 2'd1);

assign empty_fu_339_p2 = (loop_index80_reg_239 + 2'd1);

assign exitcond1_fu_396_p2 = ((empty_60_reg_272 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond812_fu_379_p2 = ((loop_index_reg_261 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond823_fu_362_p2 = ((loop_index77_reg_250 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond834_fu_345_p2 = ((loop_index80_reg_239 == 2'd3) ? 1'b1 : 1'b0);

assign grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_ap_start_reg;

assign loop_index77_cast_fu_368_p1 = loop_index77_reg_250;

assign loop_index80_cast_fu_351_p1 = loop_index80_reg_239;

assign loop_index_cast_fu_385_p1 = loop_index_reg_261;

assign num_points_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address0;

assign num_points_address1 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_address1;

assign num_points_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce0;

assign num_points_ce1 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_num_points_ce1;

assign p_cast_fu_402_p1 = empty_60_reg_272;

assign patch_stream_V_din = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_patch_stream_V_din;

assign points_address0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address0;

assign points_address1 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_address1;

assign points_ce0 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce0;

assign points_ce1 = grp_p_shadowquilt_main_loop_make_verticle_strip_fu_283_points_ce1;

assign system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatBottom_address0 = loop_index_cast_fu_385_p1;

assign system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_flatTop_address0 = loop_index77_cast_fu_368_p1;

assign system_top_ap_uint_96_512_unsigned_int_stream_ap_uint_96_0_squareAcceptance_address0 = loop_index80_cast_fu_351_p1;

always @ (posedge ap_clk) begin
    loop_index80_cast_reg_416[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    loop_index77_cast_reg_435[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    loop_index_cast_reg_454[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //system_top
