#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("apexZ0", 64, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("stop", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("ppl", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("leftRight", 1, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("n_patches_i", 32, hls_in, 4, "ap_ovld", "in_data", 1),
	Port_Property("n_patches_o", 32, hls_out, 4, "ap_ovld", "out_data", 1),
	Port_Property("n_patches_o_ap_vld", 1, hls_out, 4, "ap_ovld", "out_vld", 1),
	Port_Property("GDarray_address0", 11, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("GDarray_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("GDarray_q0", 192, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("GDn_points_address0", 3, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("GDn_points_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("GDn_points_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("patches_superpoints_address0", 15, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("patches_superpoints_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("patches_superpoints_we0", 1, hls_out, 7, "ap_memory", "mem_we", 1),
	Port_Property("patches_superpoints_d0", 64, hls_out, 7, "ap_memory", "mem_din", 1),
	Port_Property("patches_superpoints_q0", 64, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("patches_superpoints_address1", 15, hls_out, 7, "ap_memory", "MemPortADDR2", 1),
	Port_Property("patches_superpoints_ce1", 1, hls_out, 7, "ap_memory", "MemPortCE2", 1),
	Port_Property("patches_superpoints_q1", 64, hls_in, 7, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("patches_parameters_address0", 12, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("patches_parameters_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("patches_parameters_we0", 1, hls_out, 8, "ap_memory", "mem_we", 1),
	Port_Property("patches_parameters_d0", 64, hls_out, 8, "ap_memory", "mem_din", 1),
	Port_Property("patches_parameters_q0", 64, hls_in, 8, "ap_memory", "mem_dout", 1),
	Port_Property("patches_parameters_address1", 12, hls_out, 8, "ap_memory", "MemPortADDR2", 1),
	Port_Property("patches_parameters_ce1", 1, hls_out, 8, "ap_memory", "MemPortCE2", 1),
	Port_Property("patches_parameters_we1", 1, hls_out, 8, "ap_memory", "MemPortWE2", 1),
	Port_Property("patches_parameters_d1", 64, hls_out, 8, "ap_memory", "MemPortDIN2", 1),
	Port_Property("patches_parameters_q1", 64, hls_in, 8, "ap_memory", "MemPortDOUT2", 1),
};
const char* HLS_Design_Meta::dut_name = "makePatches_ShadowQuilt_fromEdges";
